language: c

env:
  matrix:
    - CUDA=6.5-14
    - CUDA=7.0-28

before_install:
    - sudo ./install.sh cuda $CUDA
    - sudo ./install.sh r
    - ./install.sh rdep
    - export CUDA_HOME=/usr/local/cuda-${CUDA%%-*}
    - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
    - export PATH=${CUDA_HOME}/bin:${PATH}

install:
    - nvcc --version
    - java -version

script:
    - make

after_failure:
    - dmesg
    - ls -R /usr/local/cuda*
